# Generated by Django 4.2.4 on 2023-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_contact_name_remove_contact_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default='username:', max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
